Models/QRCode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TaskA.Models
{
	public class QRCode
	{
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int QRId { get; set; }
        [Display(Name = "QRCode Text")]
        public string QRCodeText { get; set; }
        [Display(Name = "QRCode Image")]
        public string QRCodeImagePath { get; set; }

         public int Order_ID { get; set; }
        public virtual Order Order{ get; set; }
    }
}

Controllers/QRCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskA.Models;
using ZXing;

namespace TaskA.Controllers
{
    public class QRCodesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

 

        // GET: QRCodes
        public ActionResult Index()
        {
            var qRCodes = db.QRCodes.Include(q => q.Order);
            return View(qRCodes.ToList());
        }

        // GET: QRCodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QRCode qRCode = db.QRCodes.Find(id);
            if (qRCode == null)
            {
                return HttpNotFound();
            }
            return View(qRCode);
        }

        public ActionResult ViewPDF(int id)
        {
            var report = new Rotativa.ActionAsPdf("Details", new { id = id }) { FileName = "invoice.pdf" };


            return report;

            //return new ViewAsPdf("Invoice", new { id = id });
        }

        // GET: QRCodes/Create
        public ActionResult Create()
        {
            ViewBag.Order_ID = new SelectList(db.Orders, "Order_ID", "Tasker_ID");
            return View();
        }

        // POST: QRCodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QRId,QRCodeText,QRCodeImagePath,Order_ID")] QRCode qRCode)
        {
            if (ModelState.IsValid)
            {
                db.QRCodes.Add(qRCode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Order_ID = new SelectList(db.Orders, "Order_ID", "Tasker_ID", qRCode.Order_ID);
            return View(qRCode);
        }

        // GET: QRCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QRCode qRCode = db.QRCodes.Find(id);
            if (qRCode == null)
            {
                return HttpNotFound();
            }
            ViewBag.Order_ID = new SelectList(db.Orders, "Order_ID", "Tasker_ID", qRCode.Order_ID);
            return View(qRCode);
        }

        // POST: QRCodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QRId,QRCodeText,QRCodeImagePath,Order_ID")] QRCode qRCode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qRCode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Order_ID = new SelectList(db.Orders, "Order_ID", "Tasker_ID", qRCode.Order_ID);
            return View(qRCode);
        }

        // GET: QRCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QRCode qRCode = db.QRCodes.Find(id);
            if (qRCode == null)
            {
                return HttpNotFound();
            }
            return View(qRCode);
        }

        // POST: QRCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QRCode qRCode = db.QRCodes.Find(id);
            db.QRCodes.Remove(qRCode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/QRCodes/Create.cshtml
@model TaskA.Models.QRCode

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<br />
<br />
<br />
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QRCode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.QRCodeText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.QRCodeImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRCodeImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order_ID, "Order_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("Order_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
}

Views/QRCodes/Delete.cshtml
@model TaskA.Models.QRCode

@{
    ViewBag.Title = "Delete";
}
<br />
<br />
<br />
<br />
<br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QRCode</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.Tasker_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.Tasker_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QRCodeText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QRCodeText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QRCodeImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QRCodeImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/QRCodes/Details.cshtml
@model TaskA.Models.QRCode
@helper Truncate(string input, int length)
{
    if (input.Length <= length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>...</text>
    }
}
@{
    ViewBag.Title = "Details";
  
}

<br />
<br />
<br />
<br />
<br />
<h2><b>Invioce</b></h2>


<h2 style="text-align:center;">Current Invoice</h2>
<html>
<head>
    <meta charset="utf-8">

    <style>
        .invoice-box {
            max-width: 800px;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, .15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

            .invoice-box table {
                width: 100%;
                line-height: inherit;
                text-align: left;
            }

                .invoice-box table td {
                    padding: 5px;
                    vertical-align: top;
                }

                .invoice-box table tr td:nth-child(2) {
                    text-align: right;
                }

                .invoice-box table tr.top table td {
                    padding-bottom: 20px;
                }

                    .invoice-box table tr.top table td.title {
                        font-size: 45px;
                        line-height: 45px;
                        color: #333;
                    }

                .invoice-box table tr.information table td {
                    padding-bottom: 40px;
                }

                .invoice-box table tr.heading td {
                    background: #eee;
                    border-bottom: 1px solid #ddd;
                    font-weight: bold;
                }

                .invoice-box table tr.details td {
                    padding-bottom: 20px;
                }

                .invoice-box table tr.item td {
                    border-bottom: 1px solid #eee;
                }

                .invoice-box table tr.item.last td {
                    border-bottom: none;
                }

                .invoice-box table tr.total td:nth-child(2) {
                    border-top: 2px solid #eee;
                    font-weight: bold;
                }

        @@media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }

        /** RTL **/
        .rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }

            .rtl table {
                text-align: right;
            }

                .rtl table tr td:nth-child(2) {
                    text-align: left;
                }
    </style>
</head>
<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">

                                <div class="col-md-10">

                                    @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
                                    {
                                        <center>
                                            <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" height="250" width="250" />
                                        </center>
                                    }

                                </div>
                            </td>

                            <td>
                                Order No #:  @Html.DisplayFor(model => model.Order_ID)<br>
                                Created:  @Html.DisplayFor(model => model.Order.Order_DateTime)<br>
                                @*2020/07/23*@
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                @*20 Crest Road<br>
                                    Durban North <br>
                                    Durban 4051*@ @Truncate(Model.Order.Bookings.Quote.ServiceRender_Address, 25)
                                </td>

                                <td>

                                    @*John Doe<br>
                                        john@example.com*@
                                    @Html.DisplayFor(model => model.Order.Bookings.Book_RecipientName) <br>
                                    @Html.DisplayFor(model => model.Order.Bookings.Client.Profile_Email)
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr class="heading">
                    <td>
                        Payment Date
                    </td>

                    <td>
                    </td>
                </tr>

                <tr class="details">
                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Booking_date)
                    </td>

                    <td>
                    </td>
                </tr>

                <tr class="heading">
                    <td>
                        Details
                    </td>

                    <td>
                        Number
                    </td>
                </tr>

                <tr class="item">
                    <td>
                        Render Service category
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Quote.ServiceCat.Category)
                    </td>
                </tr>

                <tr class="item">
                    <td>
                        Render Service Hours
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Quote.Render_hours) hrs
                    </td>
                </tr>

                <tr class="item">
                    <td>
                        Distance
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Quote.Destination_Distance) Km
                    </td>
                </tr>

                <tr class="item">
                    <td>
                        Render Service Cost
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Quote.RenderService_Cost)
                    </td>
                </tr>

                <tr class="item">
                    <td>
                        Transport Cost
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Order.Bookings.Quote.Transport_Cost)
                    </td>
                </tr>
                @*<tr class="item">
                        <td>
                            Item Description
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.Bookings.Quote.Quote_Description)
                        </td>
                    </tr>*@

                @*<tr class="item last">
                        <td>
                            Distance
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.Bookings.Quote.Quote_Distance) km
                        </td>
                    </tr>*@

                <tr class="heading">
                    <td>
                        Payment
                    </td>

                    <td>
                        Total
                    </td>
                </tr>



                <tr class="total">
                    <td>
                        <b>Grand Total</b>
                    </td>

                    <td>
                        R @Html.DisplayFor(model => model.Order.Bookings.Quote.Quote_Cost)
                    </td>
                </tr>
            </table>

        </div>
    </body>
</html>
<a href='@Url.Action("ViewPDF", "QRCodes", new { id = Model.Order_ID })' class="btn btn-primary">Download As PDF</a>

Views/QRCodes/Edit.cshtml
@model TaskA.Models.QRCode

@{
    ViewBag.Title = "Edit";

}
<br />
<br />
<br />
<br />
<br />
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QRCode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.QRId)

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRCodeImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order_ID, "Order_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Order_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Order_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/QRCodes/Index.cshtml
@model IEnumerable<TaskA.Models.QRCode>

@{
    ViewBag.Title = "Index";

}
<br />
<br />
<br />
<br />
<br />
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Order.Tasker_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QRCodeText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QRCodeImagePath)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Order.Tasker_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QRCodeText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QRCodeImagePath)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.QRId }) |
                @Html.ActionLink("Details", "Details", new { id = item.QRId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.QRId })
            </td>
        </tr>
    }

</table>