Models/Quote.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography;

namespace TaskA.Models
{
    public class Quote
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Quote ID")]
        public int Quote_ID { get; set; }

        // make current (Don't show user this #ish)
        [DisplayName("Date Produced")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date_Produced { get; set; }

        [DisplayName("Desired Service")]
        public int ServiceCat_ID { get; set; }
        public virtual ServiceCat ServiceCat { get; set; }

        [Required(ErrorMessage = "Render service address is required")]
        [DisplayName("Physical address")]
        public string ServiceRender_Address { get; set; }

        [DisplayName("TaskA Coporation address")]
        public string TaskA_Address { get; set; }

        [DisplayName("Distance (km)")]
        [Range(0.0, Double.MaxValue, ErrorMessage = "Out of range")]
        public double Destination_Distance { get; set; }

        [Required(ErrorMessage = "Render service duration is required")]
        [DataType(DataType.Duration)]
        [DisplayName("Estimated rendering hours (minutes)")]
        public int Render_hours { get; set; }

        [DataType(DataType.Currency)]
        [DisplayName("Transportation Cost")]
        public decimal Transport_Cost { get; set; }

        [DataType(DataType.Currency)]
        [DisplayName("Service Rendered Cost")]
        public decimal RenderService_Cost { get; set; }

        [DataType(DataType.Currency)]
        [DisplayName("Discount")]
        public decimal Discount_Cost { get; set; }

        [DataType(DataType.Currency)]
        [DisplayName("Total cost")]
        public decimal Quote_Cost { get; set; }

        public virtual List<Booking> Bookings { get; set; }

    }
}

Controllers/QuotesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskA.Models;

namespace TaskA.Controllers
{
    public class QuotesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Quotes
        public ActionResult Index()
        {
            var quotes = db.Quotes.Include(q => q.ServiceCat);
            return View(quotes.ToList());
        }

        // GET: Quotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // GET: Quotes/Create
        public ActionResult Create()
        { 
            Quote quote = new Quote();
            quote.TaskA_Address = "42 Masobiya Mdluli Street, Durban, South Africa";
            ViewBag.ServiceCat_ID = new SelectList(db.ServiceCats, "ServiceCat_ID", "Category");
            return View(quote);
        }

        // POST: Quotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Quote_ID,Date_Produced,ServiceCat_ID,ServiceRender_Address,TaskA_Address,Destination_Distance,Render_hours,Transport_Cost,RenderService_Cost,Discount_Cost,Quote_Cost")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                var uid = User.Identity.GetUserId();
                Operations operations = new Operations();
                quote.Date_Produced = DateTime.Now;
                quote.RenderService_Cost = operations.GetHoursCost(quote);
                quote.Transport_Cost = operations.GetTravelCost(quote);
                var Price = (from c in db.Coupons
                             where c.Profile_ID == uid && c.Coupon_Status != "Used"
                             select c.Coupon_Value).FirstOrDefault();
                quote.Discount_Cost = Price;
                Coupon coupon = new Coupon();
                if(Price>0)
                {
                    coupon.Disc(uid);
                }
                quote.Quote_Cost = ((quote.RenderService_Cost + quote.Transport_Cost)-quote.Discount_Cost);
                db.Quotes.Add(quote);
                db.SaveChanges();
        
                return RedirectToAction("Details", new{id = quote.Quote_ID});
            }

            ViewBag.ServiceCat_ID = new SelectList(db.ServiceCats, "ServiceCat_ID", "Category", quote.ServiceCat_ID);
            return View(quote);
        }
        public JsonResult Getdistance(Quote quote)
        {

            return Json(quote.Destination_Distance, JsonRequestBehavior.AllowGet);
        }
        // GET: Quotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            ViewBag.ServiceCat_ID = new SelectList(db.ServiceCats, "ServiceCat_ID", "Category", quote.ServiceCat_ID);
            return View(quote);
        }

        // POST: Quotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Quote_ID,Date_Produced,ServiceCat_ID,ServiceRender_Address,TaskA_Address,Destination_Distance,Render_hours,Transport_Cost,RenderService_Cost,Quote_Cost")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ServiceCat_ID = new SelectList(db.ServiceCats, "ServiceCat_ID", "Category", quote.ServiceCat_ID);
            return View(quote);
        }

        // GET: Quotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quote quote = db.Quotes.Find(id);
            if (quote == null)
            {
                return HttpNotFound();
            }
            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quote quote = db.Quotes.Find(id);
            db.Quotes.Remove(quote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Quotes/Create.cshtml
@model TaskA.Models.Quote

@{
    ViewBag.Title = "Create";

}
<br />
<br />
<br />
<h2>Make Qoute</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <br />

    <div class="row">
        <div class="col-md-8">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.ServiceCat_ID, "Service Category", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ServiceCat_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ServiceCat_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Render_hours, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Render_hours, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Render_hours, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TaskA_Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaskA_Address, new { htmlAttributes = new { @class = "form-control", id = "travelfrom", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.TaskA_Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ServiceRender_Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ServiceRender_Address, new { htmlAttributes = new { @class = "form-control", id = "travelto" } })
                        @Html.ValidationMessageFor(model => model.ServiceRender_Address, "", new { @class = "text-danger" })
                        <br />
                        <input type="button" value="Get Distance" onclick="GetRoute()" class="btn btn-success" />
                        <input type="button" value="Reset Distance" onclick="Reset()" class="btn btn-warning" />
                    </div>
                </div>
                <br />
                <div>
                    <div id="dvDistance">
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Destination_Distance, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Destination_Distance, new { htmlAttributes = new { @class = "form-control", id = "distance", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Destination_Distance, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" onclick="calc()" value="Request Quote" class="btn btn-primary" />
                    </div>
                </div>

            </div>

        </div>	@*Show map*@
        <div class="col-md-3">
            <div id="map_canvas" style="height:350px;width:500px;">
            </div>
        </div>
        @*end show map*@
    </div>

}

<!--ENSURE YOU CHANGE TO YOUR OWN API KEY HERE !!! -->
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyA0_sFPYsqpl20d3ZsiuCc3mauXYBcZOec" type="text/javascript"></script>

<!-- code for example 1 -->
<script>

    var source, destination;
    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();
    var inputFrom = document.getElementById('travelfrom');
    var inputTo = document.getElementById('travelto');
    var distances = document.getElementById('distance');
    var options = {
        componentRestrictions: { country: ['za'] }
    };
    google.maps.event.addDomListener(window, 'load', function () {

        var autocomplete1 = new google.maps.places.Autocomplete(inputFrom, options);
        var autocomplete2 = new google.maps.places.Autocomplete(inputTo, options);

    });

    function GetRoute() {

        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        var map;
        var mapCenter = new google.maps.LatLng(-29.708421, 31.0322233);
        var myOptions =
        {
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            center: mapCenter
        };
        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
        //There should be a div with id 'map_canvas' in your html.
        //It can be done in angular directive if you are using angular


        var request = {
            origin: new google.maps.LatLng(-29.708421, 31.0322233),
            destination: new google.maps.LatLng(-29.708421, 31.0322233),
            travelMode: 'DRIVING'
        }


        directionsService.route(request, function (response, status) {
            if (status === 'OK') {
                directionsDisplay = new google.maps.DirectionsRenderer();
                directionsDisplay.setMap(map);
                directionsDisplay.setDirections(response);
                // For each route, display summary information.
            } else {
                console.log('Directions request failed due to ' + status, response);
            }
        });


        source = document.getElementById("travelfrom").value;
        destination = document.getElementById("travelto").value;
        distances.value = "";

        var request = {
            origin: source,
            destination: destination,
            travelMode: google.maps.TravelMode.DRIVING
        };

        directionsService.route(request, function (response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
            }

        });

        //*********DISTANCE AND DURATION**********************//
        var service = new google.maps.DistanceMatrixService();
        service.getDistanceMatrix({
            origins: [source],

            destinations: [destination],
            travelMode: google.maps.TravelMode.DRIVING,
            unitSystem: google.maps.UnitSystem.METRIC,
            avoidHighways: false,
            avoidTolls: false
        }, function (response, status) {

            if (status == google.maps.DistanceMatrixStatus.OK && response.rows[0].elements[0].status != "ZERO_RESULTS") {
                var distance = response.rows[0].elements[0].distance.text;
                var duration = response.rows[0].elements[0].duration.value;

                duration = parseFloat(duration / 60).toFixed(2);

                distances.value = distance.toLowerCase().replace(" km", "");
                distances.value = distances.value.split(',').join('.');
                distances.value = Math.ceil(parseFloat(distances.value));
                inputFrom.readOnly = true;
                inputTo.readOnly = true;


            } else {
                alert("Unable to find the distance via road.");
                inputFrom.readOnly = false;
                inputTo.readOnly = false;
                distance.value = "";

            }
        });
    }

    function Reset() {


        //inputFrom.value = "";
        inputTo.value = "";
        distance.value = "";
        inputFrom.readOnly = false;
        inputTo.readOnly = false
    }
</script>



Views/Quotes/Delete.cshtml
@model TaskA.Models.Quote

@{
    ViewBag.Title = "Delete";

}
<br />
<br />
<br />
<br />
<br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceCat.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceCat.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Produced)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Produced)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceRender_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceRender_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskA_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskA_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination_Distance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination_Distance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Render_hours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Render_hours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Transport_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Transport_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RenderService_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RenderService_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote_Cost)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Quotes/Details.cshtml
@model TaskA.Models.Quote

@{
    ViewBag.Title = "Details";
  
}
<br />
<br />
<br />
<br />
<br />
<h2>Quotation</h2>
<hr />
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServiceCat.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceCat.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Produced)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Produced)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceRender_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceRender_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskA_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskA_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination_Distance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination_Distance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Render_hours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Render_hours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Transport_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Transport_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RenderService_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RenderService_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount_Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote_Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote_Cost)
        </dd>

    </dl>
</div>
<div class="row">
    <a href='@Url.Action("Create", "Bookings", new { id = Model.Quote_ID }, null)' class="btn btn-success">Proceed</a>

    <a href='@Url.Action("Edit", "Quotes", new { id = Model.Quote_ID }, null)' class="btn btn-warning">Edit</a>

    <a href='@Url.Action("Delete", "Quotes", new { id = Model.Quote_ID }, null)' class="btn btn-danger">Cancel</a>
</div>


Views/Quotes/Edit.cshtml
@model TaskA.Models.Quote

@{
    ViewBag.Title = "Edit";
   

}
<br />
<br />
<br />
<br />
<br />
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quote</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Quote_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Produced, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Produced, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Produced, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceCat_ID, "ServiceCat_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceCat_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceCat_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceRender_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceRender_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceRender_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskA_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskA_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskA_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination_Distance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination_Distance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination_Distance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Render_hours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Render_hours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Render_hours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Transport_Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Transport_Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Transport_Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RenderService_Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RenderService_Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RenderService_Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quote_Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quote_Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quote_Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}